version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - photo-prestiges

  api-gateway:
    build: ./api-gateway
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
    networks:
      - photo-prestiges

  auth-service:
    restart: unless-stopped
    build: ./auth-service
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/auth
      - DB_URL=mongodb://mongo:27017/auth
      - JWT_SECRET=mysecretkey
    depends_on:
      - mongo
    networks:
      - photo-prestiges

volumes:
  mongo_data:

networks:
  photo-prestiges:
    driver: bridge
